---
version: '3'
services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  feature_server:
    container_name: feast_feature_server
    build:
      context: .
      dockerfile: feature_repo/Dockerfile
    depends_on:
      registry:
        condition: service_healthy
    ports:
      - "6566:6566"
    links:
      - redis
    healthcheck:
      test: "${DOCKER_HEALTHCHECK_TEST:-curl localhost:6566/health}"
      interval: "5s"
      retries: 5

  registry:
    container_name: registry
    image: postgres:10.5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=feast
    ports:
      - "55001:5432"
    volumes: 
      - ./feast-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5
